### ISSUE TITLE
Live Preview is always loading

### ISSUE THREAD

**Issue by hammer-wang** [CodePen/CodePen-Bug-Reporting-Only#127] opened 2016-02-26 17:16 UTC
My live preview screen cannot display anything except "loading".... 

I'm wondering whether something's wrong with my settings or my browser or my internet?

I've tried IE, Chrome and Safari. But none of them works...

Below is the screenshot. I'd appreciate it a lot if somebody could help me.

Thanks a lot.

![screen](https://dl.dropbox.com/s/ueebfxwxzd3k8p5/Screen%20Shot%202016-02-26%20at%2009.36.49.png?dl=0)

**Comment by mariemosley** [comment] 2016-02-26 17:33
Usually when this happens in every browser, it's related to a connection issue or a firewall. Try checking your browser console for errors. If you see any, please email us a screenshot at support@codepen.io and we'll take a look :)

I'm closing this issue since it's not a bug, but thanks for letting us know!

**Closed by mariemosley** 2016-02-26 17:33 UTC
