### ISSUE TITLE
No nesting in the console.

### ISSUE THREAD

**Issue by FatTone225** [CodePen/CodePen-Bug-Reporting-Only#80] opened 2016-02-04 17:53 UTC
Hey guys,

Loving the console feature but I noticed that when there are nested objects in the console there is no way to open them sometimes. Possibly after the 3rd level? Here is an example.

http://codepen.io/TonyMiri/pen/ZQMmJq?editors=1011

While building this I noticed that the nearby_weather_stations object couldn't be expanded. It is an expandable object in the browser console and just so happened to contain the data I needed, so I figured I'd bring it up. 

Keep up the great work guys.

**Comment by mariemosley** [comment] 2016-02-08 18:33
Hi @FatTone225! The console is limited to 3 levels of nesting by design, so I'm going to close this issue as it's not quite a bug. But, I have made a note of your report so the team knows there's interest in deeper nesting in the console. Thanks for letting us know!

**Closed by mariemosley** 2016-02-08 18:33 UTC
