### ISSUE TITLE
cssnext add-on: request timed out

### ISSUE THREAD

**Issue by anthonydugois** [CodePen/CodePen-Bug-Reporting-Only#27] opened 2015-12-05 16:58 UTC
When I try to compile a postcss syntax using the cssnext add-on, I get this error:

```
Request timed out. Check your postcss. Try again or contact support@codepen.io.
```

Sometimes it works, but this is rather random.

**Comment by tsabat** [comment] 2015-12-07 18:19
Are you still seeing this issue?  We're unable to reproduce it.

**Comment by chriscoyier** [comment] 2015-12-08 22:13
We can keep an eye on it. I'm gonna close this for now as it seems like it's not a persistent problem. That error is either...

1. Our servers are being slow (our fault)
1. Or, the Pen is at the edge of being too hard for us to process (we have to set a time limit so our servers don't freeze up and not processor other people's Pens)

Shooting us a link to the Pen in question is always helpful too.

**Closed by chriscoyier** 2015-12-08 22:13 UTC
