### ISSUE TITLE
[minor] forking causes editor window widths to reset

### ISSUE THREAD

**Issue by tomByrer** [CodePen/CodePen-Bug-Reporting-Only#62] opened 2016-01-22 05:29 UTC
I had the HTML & CSS editor windows widened, forked, then they reset to equidistant widths.
reproducable

**Comment by mariemosley** [comment] 2016-02-08 21:31
Can you let us know what browser you're using, and your editor layout (top, left, or right)?

**Comment by mariemosley** [comment] 2016-02-16 17:39
Closing this because we can't reproduce it. But, if you can get back to us with more detail we'll look into it again :)

**Closed by mariemosley** 2016-02-16 17:39 UTC
