### ISSUE TITLE
NPM Installing Feature?

### ISSUE THREAD

**Issue by rkhayat** [CodePen/CodePen-Bug-Reporting-Only#44] opened 2015-12-21 17:49 UTC
Not a bug, but I was hoping someone would speak to how I could use npm install etc in codepen? In Angular land it was pretty easy to hack my way to a codepen, but with React npm seems to be the 'go-to' way of handling assets / modules.

Example in question - https://github.com/skratchdot/react-bootstrap-multiselect

**Comment by mariemosley** [comment] 2015-12-21 20:06
Hi @rkhayat! I've made a note of your feature request 😀I'm closing this issue since it's not a bug.

**Closed by mariemosley** 2015-12-21 20:06 UTC

**Comment by chriscoyier** [comment] 2015-12-21 22:28
Mostly it's a matter of hosting the assets somewhere and linking to them. We have our own assets hosting feature. http://blog.codepen.io/documentation/pro-features/asset-hosting/

And requireJS even works with it: http://blog.codepen.io/2015/07/29/using-requirejs-in-pens/

But yeah sadly it's not as easy as just npm install yada yada - maybe someday!

**Comment by rkhayat** [comment] 2015-12-21 22:34
:+1:  You guys are awesome, thanks.
