### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by darryl-snow** [CodePen/CodePen-Bug-Reporting-Only#50] opened 2016-01-07 03:48 UTC
Not sure if this is even a bug, sorry, just thought it might be interesting / worth pointing out. When using a VPN (I'm in China so use my VPN 24/7) *most* pens don't load, in any browser. I just get the loading message in the #result_div. Maybe it's something to do with the connection to http://codepen.io/preprocessors? After about 20 seconds a single error appears in the console, relating to the code for the pen itself. For example:

http://codepen.io/joshbader/pen/EjXgqr

<img width="698" alt="screen shot 2016-01-07 at 11 47 33" src="https://cloud.githubusercontent.com/assets/2296711/12161732/7e03e702-b534-11e5-82c9-8c87a3797026.png">

**Comment by mariemosley** [comment] 2016-01-12 18:05
Hi Darryl! This may be related to the problem described in this issue: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/39, where something in the connection is interfering with CodePen. We're looking into ways to help prevent this, and there's some discussion of that in the thread.

I'm closing this issue because we can't reproduce it and we have a similar open issue, but thank you very much for reporting it!

**Closed by mariemosley** 2016-01-12 18:05 UTC
