### ISSUE TITLE
Minor Lovers Paging Bug

### ISSUE THREAD

**Issue by rafhun** [CodePen/CodePen-Bug-Reporting-Only#206] opened 2016-04-21 07:42 UTC
One of my blog posts (at the time of this writing) has exactly 40 lovers: http://codepen.io/rafhun/post/setting-up-a-devenv-on-a-mac#lovers

When looking at them I can see all 40 of them. Upon clicking the Next button I get the message, that there is no love yet for this pen:

![paging-bug](https://cloud.githubusercontent.com/assets/7340779/14701342/3ad0fae2-07a5-11e6-8b28-698948be1f95.gif)

Also the only way to get back to the list is to refresh the whole page.

**Comment by rachsmithcodes** [comment] 2016-04-26 16:59
A fix went out for this - also reduced the number of lovers per page to 30 as 40 was a bit intense.
Something a bit weird is going on with this post in particular because the first page returns 31 loves when other posts such as http://codepen.io/rachsmith/post/beginning-with-3d-webgl-pt-1-the-scene#lovers return 30.
I'm closing this but keeping an eye out for the paging inconsistency on other posts to see if I can reproduce elsewhere.

**Comment by rachsmithcodes** [comment] 2016-04-26 16:59
thanks for reporting!!

**Closed by rachsmithcodes** 2016-04-26 16:59 UTC
